apiVersion: v1
kind: Pod
metadata:
  name: flask-health-pod
  labels:
    app: flask-health-app
spec:
  imagePullSecrets:
  - name: dockerhub-secret
  containers:
  - name: flask-health-container
    image: pouriajalilian/flask-health-app:v3 # Your Flask app image
    ports:
    - containerPort: 5000
    # Explicitly run your Flask application using python3 and app.py
    # IMPORTANT: Ensure 'app.py' is the correct name of your Flask application file
    # and that it's at the root of your Docker image's filesystem.
    command: ["python3"]
    args: ["app.py"]
    livenessProbe:
      httpGet:
        path: /health # Probe checks this endpoint
        port: 5000
      initialDelaySeconds: 10 # Wait 5 seconds before first liveness check
      periodSeconds: 5     # Check every 5 seconds
      timeoutSeconds: 3    # Consider failure if no response in 3 seconds
      failureThreshold: 3  # After 3 consecutive failures, restart the container
    readinessProbe:
      httpGet:
        path: /health # Probe checks this endpoint
        port: 5000
      initialDelaySeconds: 10 # Wait 10 seconds before first readiness check
      periodSeconds: 5      # Check every 5 seconds
      timeoutSeconds: 3     # Consider failure if no response in 3 seconds
      failureThreshold: 3   # After 3 consecutive failures, stop sending traffic
