apiVersion: v1
kind: Service
metadata:
  name: flask-health-service
spec:
  selector:
    app: flask-health-app
  ports:
    - protocol: TCP
      name: http-metrics
      port: 80
      targetPort: 5000


